### PR TITLE
async-storage bindings

### PR DESCRIPTION
**Pull request by tatchi**
Bindings for the [async-storage](https://github.com/react-native-community/async-storage) package. Following https://github.com/reasonml-community/reason-react-native/issues/594

I have implemented them based on the [current ones](https://github.com/reasonml-community/reason-react-native/blob/master/reason-react-native/src/apis/AsyncStorage.re) but have slightly modified two of them:

- multiMerge: use `array((string, string))` instead of `array(array(string))`. Since we always pass an array of arrays containing 2 elements (key and value), I think tuple would be a better fit (like it's already done for the `multiSet)`.
- multiGet: also replaced the double arrays to an array of tuples (for the same reason). Furthermore and according to my tests, we never get back a `null` value. If a `key` does not exist, this key will still exist in the returned array but only the corresponding `value` will be `null`. That still seems strange since that's not what the doc mention: https://github.com/react-native-community/async-storage/blob/LEGACY/docs/API.md#multiget

Except from that, the rest should be the same.

I still need to create the binding for the [useAsyncStorage](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/API.md#useasyncstorage) hooks. I will address that later on.

### CODE REVIEW

**Review by cknitt — APPROVED** [review]
This looks great! Thanks! 👍

**Comment by tatchi** [comment]
I've added the binding from the [useAsyncStorage](https://github.com/react-native-community/async-storage/blob/LEGACY/docs/API.md#useasyncstorage) hook.

I've used the [Object 2](https://bucklescript.github.io/docs/en/object-2) approach from bucklescript (as used for the [NetInfo](https://github.com/reasonml-community/reason-react-native/blob/1bbb716dff888ad67b06641c67a31aa3e01f7c49/%40reason-react-native/netinfo/src/ReactNativeNetInfo.re#L49) bindings).

I would probably have prefered to use normal record but not sure how to properly manage that. I've tried the approach below but then it generates JS codes (so no more zero cost):

```reason
type asyncStorageStateInternal = {
  .
  [@bs.meth] "getItem": unit => Js.Promise.t(Js.Null.t(string)),
  [@bs.meth] "setItem": string => Js.Promise.t(unit),
  [@bs.meth] "mergeItem": string => Js.Promise.t(unit),
  [@bs.meth] "removeItem": unit => Js.Promise.t(unit),
};

[@bs.module "@react-native-community/async-storage"]
external _useAsyncStorage: string => asyncStorageStateInternal =
  "useAsyncStorage";

type asyncStorageState = {
  getItem: unit => Js.Promise.t(Js.Null.t(string)),
  setItem: string => Js.Promise.t(unit),
  mergeItem: string => Js.Promise.t(unit),
  removeItem: unit => Js.Promise.t(unit),
};
let useAsyncStorage = (key: string) => {
  let hook = _useAsyncStorage(key);
  {
    getItem: _ => hook##getItem(),
    setItem: value => hook##setItem(value),
    mergeItem: value => hook##mergeItem(value),
    removeItem: _ => hook##removeItem(),
  };
};
```

What do you think ?

**Comment by MoOx** [comment]
Zero cost bindings are preferable not only for perf, but also to avoid an additional discrepancies between the original lib & the bindings. Any helper that inserts itself into two layers potentially breaks things so avoiding that is better whenever it's possible.

Awesome work. I will merge that & release it soon.

**Comment by MoOx** [comment]
Merging, I will make a release as soon as we have template setup & this repo adjusted if needed (to make release & tags easy to push).
Thanks for this awesome work!

**Pull request merged**
